### ISSUE TITLE
[bug][1.20.4][0.5.3]An error was reported while mining tools that do not contain the specified enchantment

### ISSUE THREAD

**Issue by zorippl** [Skjolberg/SimpleBlockRegenPlugin#5]
diamond_ore settings:
  enchantments:
    - LURE;10
  tool-required:
    - IRON_PICKAXE

i use an iron_pickaxe with out any enchantment, i can destory the diamond_ore in region

logs here:

`[21:33:49 ERROR]: Could not pass event BlockBreakEvent to SimpleBlockRegen v0.5.3-SNAPSHOT
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at net.shibacraft.simpleblockregen.events.blockevent.blockbreak.action.ActionManager.checkEnchants(ActionManager.java:134) ~[SimpleBlockRegen-0.5.3-SNAPSHOT.jar:?]
        at net.shibacraft.simpleblockregen.events.blockevent.blockbreak.action.BlockBreakAction.mineAction(BlockBreakAction.java:105) ~[SimpleBlockRegen-0.5.3-SNAPSHOT.jar:?]
        at net.shibacraft.simpleblockregen.events.blockevent.blockbreak.BlockBreakListener.accept(BlockBreakListener.java:198) ~[SimpleBlockRegen-0.5.3-SNAPSHOT.jar:?]
        at net.shibacraft.simpleblockregen.events.blockevent.blockbreak.BlockBreakListener.accept(BlockBreakListener.java:31) ~[SimpleBlockRegen-0.5.3-SNAPSHOT.jar:?]
        at net.shibacraft.simpleblockregen.module.EventModule.lambda$setupBlockBreak$0(EventModule.java:139) ~[SimpleBlockRegen-0.5.3-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-381]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-381]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-381]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:298) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-381]`

**Comment by Skjolberg** [comment]
Hi,

Join the Discord and verify yourself pls, thanks.

**Comment by zorippl** [comment]
discord link in github is still out of date...plz

**Comment by Skjolberg** [comment]
> discord link in github is still out of date...plz

On the official spigot website, i.e, you can find it: 

https://www.spigotmc.org/resources/simpleblockregen-premium-%E2%9C%85-create-automatic-regeneration-regions-%E2%9B%8F%EF%B8%8F.103286/
